// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace AktivReader.Database.Models;

public partial class Club
{
    public int Id { get; set; }

    public DateTime CreationDate { get; set; }

    public string ClubName { get; set; }
}