// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Nex.AktivWinner.Reader.Database.Configurations;

#nullable disable

namespace Nex.AktivWinner.Reader.Database;

public partial class SKCMatchesContext : DbContext
{
    public SKCMatchesContext(DbContextOptions<SKCMatchesContext> options)
        : base(options)
    {
       
    }

    public virtual DbSet<Club> Clubs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new ClubConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer("Data Source=(localdb)\\mssqllocaldb ;Initial Catalog=SKCMatches;Integrated Security=True");
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
