# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Anzeigen der Ordnerstruktur
      run: ls -R
    - name: Restore dependencies
      run: dotnet restore AktivCrawler.sln
    - name: Build
      run: dotnet build AktivCrawler.sln --no-restore
    - name: Test
      run: dotnet test AktivCrawler.sln --no-build --verbosity normal
