name: CI on push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_ubuntu:
    name: Build on Ubuntu latest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/AktivCrawler
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x

      - name: Restore dependencies
        run: dotnet restore ./AktivCrawler.sln
          
      - name: Build Application 1
        run: dotnet build ./AktivCrawler/AktivCrawler.csproj --configuration Release --no-restore
      
      - name: Build Application 2
        run: dotnet build ./AktivManager/AktivManager.csproj --configuration Release --no-restore
      
      - name: Build Application 3
        run: dotnet build ./AktivReader/AktivReader.csproj --configuration Release --no-restore

  build_windows:
    name: Build on Windows latest
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src/AktivCrawler
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x
          
      - name: Restore dependencies
        run: dotnet restore ./AktivCrawler.sln

      - name: Build Application 1
        run: dotnet build ./AktivCrawler/AktivCrawler.csproj --configuration Release --no-restore
      
      - name: Build Application 2
        run: dotnet build ./AktivManager/AktivManager.csproj --configuration Release --no-restore
      
      - name: Build Application 3
        run: dotnet build ./AktivReader/AktivReader.csproj --configuration Release --no-restore
