name: CI on push
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: '9.x.x'

jobs:
  build_ubuntu:
    name: Build on Ubuntu latest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/Nex.AktivWinner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore
          
      - name: Build Application 1
        run: dotnet build ./Nex.AktivWinner.Crawler/Nex.AktivWinner.Crawler.csproj --configuration Release --no-restore
      
      - name: Build Application 2
        run: dotnet build ./Nex.AktivWinner.Reader/Nex.AktivWinner.Reader.csproj --configuration Release --no-restore

  build_windows:
    name: Build on Windows latest
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src/Nex.AktivWinner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build Application 1
        run: dotnet build ./Nex.AktivWinner.Crawler/Nex.AktivWinner.Crawler.csproj --configuration Release --no-restore
      
      - name: Build Application 2
        run: dotnet build ./Nex.AktivWinner.Reader/Nex.AktivWinner.Reader.csproj --configuration Release --no-restore
